apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  labels:
    app.kubernetes.io/name: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-api
    spec:
      containers:
        - name: api
          image: ghcr.io/belltigerlee/smurf-child@sha256:4f4b1535e8a79a9b84518a236fca8e7497c2d0f08d6c1d9d63f01813f8f2a152
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: sample-api
